[package]
name = "orhanwm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = "0.3.4"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
